server:
  port: 8081

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  management:
    endpoints:
      web:
        exposure:
          include: health,info